<center><h1 style="color:#173F8A;"> Cálculo Científico I, MAT2605, 2025-2 </h1></center>
<h3 style="color:#173F8A;text-align:left;"> Facultad de Matemáticas<br>  Pontificia Universidad Catolica de Chile <br>  </h3>
<h3 style="color:#0176DE;text-align:left;"> Profesor: Manuel A. Sanchez<br> </h3>
<h4 style="color:#0176DE;text-align:left;"> Ayudantes: Tomás Malfetano (tomas.malfetano@uc.cl), Diego Vera (dva@uc.cl)<br> </h4>
<hr style="border:2px solid #03122E"> </hr>

<!-- Palette colors UC: celeste:#0176DE, azul #173F8A, azul oscuro: #03122E, amarillo: #FEC60D, amarillo oscuro: #E3AE00 -->
<!--
<figure>
<img align ="right" src="IMClogo.png" alt="logo" width="200" height="400"><br><br><br><br><br>
</figure>
 -->
<!-- Palette colors UC:
Primaria: 
celeste:#0176DE, azul #173F8A, azul oscuro: #03122E, amarillo: #FEC60D, amarillo oscuro: #E3AE00 
Secundaria
gris oscuro: #707070
-->

# Ayudantía 2

In [1]:
import numpy as np

## Problema 1

La norma de Frobenius para una matriz $A$ de $n\times n$ está dada por
$$
\|A\|_F = 
\left(
\sum_{i=1}^n\sum_{j=1}^n
|a_{ij}|^2
\right)^{1/2} .
$$

1. Demuestre que $\|\cdot\|_F$ es una norma matricial.
2. Muestre que, para cualquier matriz $A\in \mathbb{R}^{n\times n}$,
$$
\|A\|_2 \leq
\|A\|_F \leq
n^{1/2}\|A\|_2
$$
3. Muestre que la norma de Frobenius no es una norma matricial inducida (*Hint: muestre primero que, para toda norma matricial inducida se cumple que $\|I\|=1$*)

## Problema 2

Considere el siguiente sistema lineal:
$$
\begin{pmatrix}
1 & 1 + \epsilon^2 \\
1 & 1
\end{pmatrix}
x = \begin{pmatrix}
b_1 \\
b_2
\end{pmatrix}
$$

1. Encuentre una expresión para el número de condición de la matriz del sistema con respecto a la norma infinito.
2. Encuentra una expresión para la solución $x$ ¿Que sucede con la solución cuando $\epsilon \to 0$? ¿Que relación tiene esto con el condicionamiento de la matriz? 
3. Considere $b_1 = b_2$. Analice que sucede cuando se perturba $b$ en una dirección tal que la primera componente de $b + \Delta b$ es igual que la segunda ¿Se siguen respetando las desigualdades asociadas al sistema perturbado?

 

## Problema 3

Programe el método de eliminación Gaussiana con y sin pivoteo. Aplique el método con el sistema dado por la matriz $A\in \mathbb{R}^{n\times n}$ definida por,
$$
A_{ij} =
\begin{cases}
i\cdot j & \text{si } i \text{ es divisible por }j, \\
1 & \text{en otro caso}
\end{cases},\quad
\text{para }i,j=1,\dots, n,
$$
y el vector $b\in \mathbb{R}^n$ dado por $b_i = i$ para todo $i=1,\dots, n$.

## Disclaimer

In [2]:
matriz = np.array([[1, 2], [1, 2]])
matriz2 = np.array([[1, 2], [1, 2]])
matriz3 = np.array([[1, 2], [1, 2]])

# Mala práctica
def modificar_matriz(matriz):
    n = matriz.shape[0]
    for i in range(n):
        matriz[i, :] = 10*matriz[i, :]
    return matriz

def modificar_matriz2(matriz2):
    matriz2 = matriz2*10
    return matriz2

# Buena práctica
# # Definir las variables de la función con un nombre distinto al de variables globales
# # Ocupar np.copy()

def modificar_matriz3(M_):
    M = np.copy(M_)
    # M = M_
    n = M.shape[0]
    for i in range(n):
        M[i, :] = 10*M[i, :]
    return M

In [3]:
""" 
Al ejecutar esta celda varias veces se 
observa el problema con la primera función.
"""

print(modificar_matriz(matriz))

print(modificar_matriz2(matriz2))

print(modificar_matriz3(matriz3))

[[10 20]
 [10 20]]
[[10 20]
 [10 20]]
[[10 20]
 [10 20]]


## Solución Problema 3

In [ ]:
"""
Eliminación Gaussiana SIN Pivoteo. Este método asume que no aparecen ceros en la diagonal.
"""
def GE_no_pivot(A_, b_):
    n = len(b_) # dimensión del sistema
    """
    Primero transformamos el sistema a uno con una matriz triangular superior.
    """
    # Aqui se almacena la matriz triangular superior
    A = np.copy(A_)
    # Aqui se almacena el vector derecho del nuevo sistema
    b = np.copy(b_)
    
    # Iteramos fila por fila
    for i in range(n):
        # Iteramos desde la fila i+1 hasta n
        for k in range(i+1, n):
            # Calculamos el pivote
            pivote = A[k, i] / A[i, i]
            # Realizamos E_k --> E_k - pivote*E_i
            A[k, :]  = A[k, :] - pivote * A[i, :]
            b[k] = b[k] - pivote * b[i]
            
    """
    Ahora realizamos substitución regresiva.
    """
    # Iteramos desde la última fila hacia arriba
    for i in range(n-1, -1, -1):
        # Dividimos los valores de la fila i por el valor en la diagonal
        m = A[i, i]
        A[i, :] = A[i, :] / m
        b[i] = b[i] / m

        # Iteramos desde la fila i - 1 a la fila 0
        for k in range(i-1, -1, -1):
            # Realizamos E_k --> E_k - A[k, i]*E_i
            m = A[k, i]
            A[k, :] = A[k, :] - m*A[i, :]
            b[k] = b[k] - m*b[i]

    return A, b

In [5]:
"""
Eliminación Gaussiana CON Pivoteo. 
"""

def GE_with_pivot(A_, b_):
    n = len(b_) # dimensión del sistema
    """
    Primero transformamos el sistema a uno con una matriz triangular superior.
    """
    # Aqui se almacena la matriz triangular superior
    A = np.copy(A_)
    # Aqui se almacena el vector derecho del nuevo sistema
    b = np.copy(b_)
    
    # Iteramos fila por fila
    for i in range(n):
        # Primero realizamos el pivoteo
        """
        Esta sección es la única distinta a la parte anterior. Recorremos desde 
        la fila i + 1 hasta el final, buscando, la fila que en la columna i tenga el 
        mayor valor en valor absoluto (sea esta la fila l). Luego hacemos el intercambio 
        de filas entre i y l; también en el vector b.
        """
        # buscamos la fila para hacer el intercambio
        val = abs(A[i, i]) 
        index = i
        for k in range(i + 1, n):
            if abs(A[k, i]) > val:
                val = abs(A[k, i])
                index = k
        # Realizamos el intercambio
        aux_fila = A[i, :] 
        aux_b = b[i]

        A[i, :] = A[index, :]
        b[i] = b[index]

        A[index, :] = aux_fila
        b[index] = aux_b

        # Iteramos desde la fila i+1 hasta n
        for k in range(i+1, n):
            # Calculamos el pivote
            pivote = A[k, i] / A[i, i]
            # Realizamos E_k --> E_k - pivote*E_i
            A[k, :]  = A[k, :] - pivote * A[i, :]
            b[k] = b[k] - pivote * b[i]
            
    """
    Ahora realizamos substitución regresiva.
    """
    # Iteramos desde la última fila hacia arriba
    for i in range(n-1, -1, -1):
        # Dividimos los valores de la fila i por el valor en la diagonal
        m = A[i, i]
        A[i, :] = A[i, :] / m
        b[i] = b[i] / m

        # Iteramos desde la fila i - 1 a la fila 0
        for k in range(i-1, -1, -1):
            # Realizamos E_k --> E_k - A[k, i]*E_i
            m = A[k, i]
            A[k, :] = A[k, :] - m*A[i, :]
            b[k] = b[k] - m*b[i]

    return A, b

In [20]:
dim = 10

A = np.zeros((dim, dim))

n_filas, n_columnas = A.shape
print(f"La Matriz tiene {n_filas} filas y {n_columnas} columnas")

for i in range(n_filas):
    for j in range(n_columnas):
        if (j+1)%(i+1) == 0:
            A[i,j] = (i+1)*(j+1)
        else:
            A[i,j] = 1

b = np.linspace(1, dim, dim)

print(f"Buscamos resolver el sistema Ax = b, donde \n A =\n {A},\n y b =\n {b}.")


La Matriz tiene 10 filas y 10 columnas
Buscamos resolver el sistema Ax = b, donde 
 A =
 [[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  1.   4.   1.   8.   1.  12.   1.  16.   1.  20.]
 [  1.   1.   9.   1.   1.  18.   1.   1.  27.   1.]
 [  1.   1.   1.  16.   1.   1.   1.  32.   1.   1.]
 [  1.   1.   1.   1.  25.   1.   1.   1.   1.  50.]
 [  1.   1.   1.   1.   1.  36.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.  49.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.  64.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.  81.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1. 100.]],
 y b =
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.].


In [34]:
x = np.linalg.solve(A, b)
print(f"La solución entregada por np.linalg.solve, redondeada:\n x = {np.round(x, 3)}\n")

A_GE_no_pivot, x_GE_no_pivot = GE_no_pivot(A, b)
print(f"La solución entregada por GE_no_pivot, redondeada:\n x = {np.round(x_GE_no_pivot, 3)}\n")

A_GE_with_pivot, x_GE_with_pivot = GE_with_pivot(A, b)
print(f"La solución entregada por GE_with_pivot, redondeada:\n x = {np.round(x_GE_with_pivot, 3)}\n")

print(f"Verificamos que el error absoluto para ambos métodos es casi cero:\n " + 
      f" error_GE_no_pivot = {np.linalg.norm(b - A @ x_GE_no_pivot)}\n " + 
      f" error_GE_with_pivot = {np.linalg.norm(b - A @ x_GE_with_pivot)}")

La solución entregada por np.linalg.solve, redondeada:
 x = [-8.25  -1.198 -0.17   0.27   0.167  0.395  0.309  0.251  0.21   0.18 ]

La solución entregada por GE_no_pivot, redondeada:
 x = [-8.25  -1.198 -0.17   0.27   0.167  0.395  0.309  0.251  0.21   0.18 ]

La solución entregada por GE_with_pivot, redondeada:
 x = [-8.25  -1.198 -0.17   0.27   0.167  0.395  0.309  0.251  0.21   0.18 ]

Verificamos que el error absoluto para ambos métodos es casi cero:
  error_GE_no_pivot = 4.803559250984066e-15
  error_GE_with_pivot = 4.803559250984066e-15


In [32]:
print(f"Notamos que la matriz que retornan los métodos es la identidad: \n A_GE_no_pivot = \n{A_GE_no_pivot}\n A_GE_with_pivot = \n{A_GE_with_pivot}")

Notamos que la matriz que retornan los métodos es la identidad: 
 A_GE_no_pivot = 
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
 A_GE_with_pivot = 
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
