<center><h1 style="color:#173F8A;"> Cálculo Científico I, MAT2605, 2025-2 </h1></center>
<h3 style="color:#173F8A;text-align:left;"> Facultad de Matemáticas<br>  Pontificia Universidad Catolica de Chile <br>  </h3>
<h3 style="color:#0176DE;text-align:left;"> Profesor: Manuel A. Sanchez<br> </h3>
<h4 style="color:#0176DE;text-align:left;"> Ayudantes: Tomás Malfetano (tomas.malfetano@uc.cl), Diego Vera (dva@uc.cl)<br> </h4>
<hr style="border:2px solid #03122E"> </hr>

<!-- Palette colors UC: celeste:#0176DE, azul #173F8A, azul oscuro: #03122E, amarillo: #FEC60D, amarillo oscuro: #E3AE00 -->
<!--
<figure>
<img align ="right" src="IMClogo.png" alt="logo" width="200" height="400"><br><br><br><br><br>
</figure>
 -->
<!-- Palette colors UC:
Primaria: 
celeste:#0176DE, azul #173F8A, azul oscuro: #03122E, amarillo: #FEC60D, amarillo oscuro: #E3AE00 
Secundaria
gris oscuro: #707070
-->

# Ayudantía 4

In [2]:
import numpy as np

# Problema 1

Considere la matriz

$$
A = 
\begin{pmatrix}
1 & 1 + \varepsilon \\
1 - \varepsilon & 1
\end{pmatrix}\, \text{, y el vector }\, 
b = 
\begin{pmatrix}
2 \\
2
\end{pmatrix}
$$
donde $\varepsilon \in \mathbb{R}$.

1.  Encuentre la solución exacta del sistema $Ax = b$.
2.  Considere $\alpha > 0$ y $\Delta b = \alpha (1, 1)^T$. Calcule $\Delta x$ tal que $A(x + \Delta x) = b + \Delta b$.
3.  Muestre que 
$$
\|\Delta x\|_\infty \leq
\frac{(2 + \varepsilon)^2}{\varepsilon^2}\|\Delta b\|_\infty
$$

# Problema 2

Problema 16 pag42 de la lista. Dejar ver la convergencia de la matriz anterior como propuesto.

Para $a\in \mathbb{R}$ consideremos el sistema lineal $Ax=b$ con 

$$
A = 
\begin{pmatrix}
a & -2 \\
-2 & 4
\end{pmatrix}\, \text{, y }\, 
b = 
\begin{pmatrix}
2 \\
2
\end{pmatrix}
$$

1.  De condiciones necesarias y suficientes para el parámetro $a$ tal que los métodos de Jacobi  y Gauss-Seidel convergen.
2.  Para el caso $a = 4$ ¿ambos métodos convergen? Sin utilizar la solución exacta, establezca una cota superior para el número de iteraciones necesarias para asegurar que el error en norma infinita es menor a $10^{-3}$. Considere como vector inicial a $x^{0} = (1, 0)^T$.
3.  **Propuesto:** Para el sistema de la pregunta anterior, de condiciones necesarias para el parámetro $\varepsilon$ tal que los métodos de Jacobi y Gauss-Seidel convergen. 

# Problema 3

Recuerde el algoritmo iterativo de Richardson con parámetro $\omega \in \mathbb{R}$ para resolver el problema $Ax = b$.

1.  Exprese el método en la forma $x^{k+1} = Tx^{k} + c$ y derive una expresión para la i-ésima componente de $x^{k+1}$.
2.  Dado un valor inicial $x^0$, escriba un pseudocódigo del algoritmo, considerando la cantidad de iteraciones como una entrada de este.
3.  Determine la cantidad de operaciones del algoritmo completo para una cantidad arbitraria de iteraciones. Ahora considere que el parámetro $\omega$ tiene un valor distinto en cada iteración, es decir, $\omega := \omega_k$ ¿Como cambia el pseudocódigo?¿Cual es la cantidad de operaciones del nuevo algoritmo?

# Problema 4



Considere las siguientes matrices simétricas:

$$
A_1 = 
\begin{pmatrix}
12 & 4 & 3 \\
4 & 2 & -1 \\
3 & -1 & 7
\end{pmatrix}
$$

$$
A_2 = 
\begin{pmatrix}
5 & -2 & -3 \\
-2 & -9 & -4 \\
-3 & -4 & 1
\end{pmatrix}
$$

$$
A_3 = 
\begin{pmatrix}
1 & 2 & 3 \\
1 & 0 & 1 \\
0 & 3 & 2
\end{pmatrix}
$$

Programe el método de Cholesky y utilícelo para verificar numéricamente que las matrices son definidas positivas.


In [39]:
def cholesky(A_):
    n, m = A_.shape
    if n != m:
        print('La matriz no es cuadrada')
        return None
    
    # Definimos donde guardaremos L
    L = np.zeros((n, n))

    # Iteramos
    for k in range(n):
        for i in range(k+1):
            if i == k: # i = k
                L[i, i] = np.sqrt(A_[i, i] - np.sum([L[i, j]**2 for j in range(i)]))
            else: # i < k
                L[k, i] = (1/L[i, i]) * (A_[i, k] - np.sum([L[i, j]*L[k, j] for j in range(i)]))
    return L

In [40]:
A1 = np.array([[12, 4, 3], 
               [4, 2, -1],
               [3, -1, 7]])

L1 = cholesky(A1)
print(L1)
print(L1@L1.T)

[[ 3.46410162  0.          0.        ]
 [ 1.15470054  0.81649658  0.        ]
 [ 0.8660254  -2.44948974  0.5       ]]
[[12.  4.  3.]
 [ 4.  2. -1.]
 [ 3. -1.  7.]]


In [52]:
A2 = np.array([[5, -2, -3], 
               [-2, -9, -4], 
               [-3, -4, 1]])

print(np.linalg.eig(A2)[0])

[-10.93550447   6.60675077   1.3287537 ]


In [ ]:
L2 = cholesky(A2)
print(L2)
print(L2@L2.T)

[[ 2.23606798  0.          0.        ]
 [-0.89442719         nan  0.        ]
 [-1.34164079         nan         nan]]
[[ 5. nan nan]
 [nan nan nan]
 [nan nan nan]]


C:\Users\diego\AppData\Local\Temp\ipykernel_15308\1821734469.py:14: RuntimeWarning: invalid value encountered in sqrt
  L[i, i] = np.sqrt(A_[i, i] - np.sum([L[i, j]**2 for j in range(i)]))


In [43]:
A3 = np.array([[1, 2, 3], 
               [1, 0, 1], 
               [0, 3, 2]])
L3 = cholesky(A3)
print(L3)
print(L3@L3.T)

[[ 1.  0.  0.]
 [ 2. nan  0.]
 [ 3. nan nan]]
[[ 1. nan nan]
 [nan nan nan]
 [nan nan nan]]


C:\Users\diego\AppData\Local\Temp\ipykernel_15308\1821734469.py:14: RuntimeWarning: invalid value encountered in sqrt
  L[i, i] = np.sqrt(A_[i, i] - np.sum([L[i, j]**2 for j in range(i)]))


Como obsevamos, para las matrices $A_2$ y $A_3$ el algoritmo presenta problemas, ya que estas matrices no son, al mismo tiempo, simétricas y definidas positivas. Probamos modificando el tipo de variable en la matriz donde guardamos nuestro resultado.

In [44]:
def cholesky2(A_):
    n, m = A_.shape
    if n != m:
        print('La matriz no es cuadrada')
        return None
    
    # Definimos donde guardaremos L
    L = np.zeros((n, n), dtype=complex)

    # Iteramos
    for k in range(n):
        for i in range(k+1):
            if i == k: # i = k
                L[i, i] = np.sqrt(A_[i, i] - np.sum([L[i, j]**2 for j in range(i)]))
            else: # i < k
                L[k, i] = (1/L[i, i]) * (A_[i, k] - np.sum([L[i, j]*L[k, j] for j in range(i)]))
    return L

In [53]:
A2 = np.array([[5, -2, -3], 
               [-2, -9, -4], 
               [-3, -4, 1]])
L2 = cholesky2(A2)
print(L2)
print(L2@L2.T)
print(np.real(L2@L2.T))

[[ 2.23606798+0.j          0.        +0.j          0.        +0.j        ]
 [-0.89442719+0.j          0.        +3.13049517j  0.        +0.j        ]
 [-1.34164079+0.j          0.        +1.66107907j  1.39970842+0.j        ]]
[[ 5.+0.j -2.+0.j -3.+0.j]
 [-2.+0.j -9.+0.j -4.+0.j]
 [-3.+0.j -4.+0.j  1.+0.j]]
[[ 5. -2. -3.]
 [-2. -9. -4.]
 [-3. -4.  1.]]


In [49]:
A3 = np.array([[1, 2, 3], 
               [1, 0, 1], 
               [0, 3, 2]])
L3 = cholesky2(A3)
print(L3)
print(L3@L3.T)
print(np.real(L3@L3.T))

[[1.+0.j        0.+0.j        0.+0.j       ]
 [2.+0.j        0.+2.j        0.+0.j       ]
 [3.+0.j        0.+2.5j       0.+0.8660254j]]
[[1.+0.j 2.+0.j 3.+0.j]
 [2.+0.j 0.+0.j 1.+0.j]
 [3.+0.j 1.+0.j 2.+0.j]]
[[1. 2. 3.]
 [2. 0. 1.]
 [3. 1. 2.]]
