<center><h1 style="color:#0098E9;"> 3. Factorizacion QR </h1></center>
  
<center><h3 style="color:#0098E9;"> Manuel A. Sanchez</h3></center>
<center><h3 style="color:#0098E9;"> Pontificia Universidad Catolica de Chile</h3></center>
<hr style="border:2px solid gray"> </hr>

In [1]:
import numpy as np
from numpy.linalg import qr

## Ejemplo 1.

\begin{equation}
A = 
\begin{pmatrix}
-1&-1&1\\
1&3&3&\\
1&-1&5 \\
-1&3&7
\end{pmatrix}
\end{equation}

In [2]:
A = np.array([[-1,-1,1],[1,3,3],[-1,-1,5],[1,3,7]]) 
[Q,R]= qr(A)
print("Q:\n", Q)
print("R:\n", R)

Q:
 [[-0.5 -0.5  0.5]
 [ 0.5 -0.5  0.5]
 [-0.5 -0.5 -0.5]
 [ 0.5 -0.5 -0.5]]
R:
 [[ 2.  4.  2.]
 [ 0. -2. -8.]
 [ 0.  0. -4.]]


In [3]:
print("Q*R:\n",Q@R)

Q*R:
 [[-1. -1.  1.]
 [ 1.  3.  3.]
 [-1. -1.  5.]
 [ 1.  3.  7.]]


<h2 style="color:#FF5CA8;"> Algoritmo QR </h2>

In [4]:

def iteracion_qr(A,MAX_ITER):
    Ak = A.copy()
    S = np.eye(A.shape[0])
    for k in range(0,MAX_ITER):
        [Q,R] = qr(Ak)
        Ak = R@Q
        S = S@Q
        print("Ak:\n",Ak)
    #end for
    return Ak, S

## Ejemplo

\begin{equation}
A = 
\begin{pmatrix}
2&1\\
2&3
\end{pmatrix}
\end{equation}

In [5]:
A = np.array([[2,1],[2,3]])

In [6]:
np.set_printoptions(precision=4)
#[T, S] = iteracion_qr(A,30)

In [8]:
#S@T@np.linalg.inv(S)

## Ejemplo

\begin{equation}
A = 
\begin{pmatrix}
2&1&0 \\
1&3&-1 \\
0&-1&6 
\end{pmatrix}
\end{equation}

In [9]:
A = np.array([[2,1,0],[1,3,-1],[0,-1,6]])

In [10]:
#[T2, S2] = iteracion_qr(A, 100)

In [11]:
#S2@T2@S2.T

## Hessenberg

In [12]:
from scipy.linalg import hessenberg
H, Q = hessenberg(A, calc_q=True)
print(H)
print(Q)

[[ 2.  1.  0.]
 [ 1.  3. -1.]
 [ 0. -1.  6.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0. -0.  1.]]


In [57]:
A = np.array([[10,1,1],[1,2,1],[1,1,14]])
np.linalg.eig(A)


(array([14.3544,  9.8317,  1.814 ]),
 array([[ 0.244 ,  0.9632,  0.1123],
        [ 0.0978,  0.0907, -0.9911],
        [ 0.9648, -0.2528,  0.0721]]))

In [58]:
H, Q = hessenberg(A, calc_q=True)
print(H)
print(Q)

[[ 1.0000e+01 -1.4142e+00  2.0293e-17]
 [-1.4142e+00  9.0000e+00 -6.0000e+00]
 [ 0.0000e+00 -6.0000e+00  7.0000e+00]]
[[ 1.      0.      0.    ]
 [ 0.     -0.7071 -0.7071]
 [ 0.     -0.7071  0.7071]]


In [59]:
MAX_ITER = 10
def inverse_iteration(A, x0, mu):
    K = A-mu*np.eye(A.shape[0])
    Kinv = np.linalg.inv(K)
    x     = []
    gamma = []
    x0 = x0/np.linalg.norm(x0)
    x.append(x0)
    gamma.append(mu)
    k = 1
    while k < MAX_ITER:
        w = Kinv.dot(x[k-1])
        xk = w/np.linalg.norm(w)
        gammak = xk.dot(A.dot(xk))
        
        x.append(xk)
        gamma.append(gammak)
        k+=1
    return gamma, x

In [60]:
inverse_iteration(A, np.array([1,1,1]), 9)


([9,
  10.0,
  9.837209302325581,
  9.831822759315205,
  9.831677133558998,
  9.83167341315568,
  9.831673320625416,
  9.831673318355891,
  9.831673318300641,
  9.831673318299302],
 [array([0.5774, 0.5774, 0.5774]),
  array([1., 0., 0.]),
  array([ 0.9705,  0.1078, -0.2157]),
  array([ 0.9649,  0.0898, -0.2468]),
  array([ 0.9635,  0.091 , -0.2519]),
  array([ 0.9633,  0.0907, -0.2527]),
  array([ 0.9632,  0.0907, -0.2528]),
  array([ 0.9632,  0.0907, -0.2528]),
  array([ 0.9632,  0.0907, -0.2528]),
  array([ 0.9632,  0.0907, -0.2528])])

In [61]:
inverse_iteration(H, np.array([1,1,1]), 10)

([10,
  9.82065353455744,
  9.83166876828169,
  9.831673316548738,
  9.831673318298785,
  9.831673318299268,
  9.831673318299266,
  9.831673318299266,
  9.831673318299266,
  9.831673318299263],
 [array([0.5774, 0.5774, 0.5774]),
  array([-0.9656, -0.1425,  0.2177]),
  array([ 0.9634,  0.115 , -0.2422]),
  array([-0.9632, -0.1147,  0.2429]),
  array([ 0.9632,  0.1147, -0.2429]),
  array([-0.9632, -0.1147,  0.2429]),
  array([ 0.9632,  0.1147, -0.2429]),
  array([-0.9632, -0.1147,  0.2429]),
  array([ 0.9632,  0.1147, -0.2429]),
  array([-0.9632, -0.1147,  0.2429])])

In [46]:
import numpy as np
from numpy.linalg import qr
A = np.array([[0,1],[1,0]])

In [47]:
mu = -1
Q, R = qr(A-mu*np.eye(2))
R@Q+mu*np.eye(2)

array([[ 1.0000e+00,  0.0000e+00],
       [ 3.3547e-17, -1.0000e+00]])

In [62]:
y = np.array([1/np.sqrt(6)-11/np.sqrt(12), -1/np.sqrt(6), 2/np.sqrt(6)-1/(3*np.sqrt(3))])
x = y/np.linalg.norm(y)


In [64]:
print(y/np.linalg.norm(y))
print(x.dot(H.dot(x)))

[-0.9656 -0.1425  0.2177]
9.820653534557438
